services:
  - type: web
    name: tabulador-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_PORT
        value: 5432
      - key: DB_HOST
        value: dpg-cnhb5rnqd2ns73fu10a0-a
      - key: DB_DATABASE
        value: tabulador_pg
      - key: DB_USER
        value: tabulador_user
      - key: DB_PASSWORD
        sync: false
      - key: HASH_SALT
        value: 10
      - key: JWT_SECRET
        generateValue: true
    buildFilter:
      paths:
        - package.json
        - src/**
        - nest-cli.json
        - tsconfig.json
        - tsconfig.build.json
    autoDeploy: false

databases:
  - name: tabulador-db
    plan: free
    databaseName: tabulador_pg
    user: tabulador_user