services:
  - type: web
    name: tabulador-api
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_PORT
        fromDatabase:
          name: tabulador-db
          property: port
      - key: DB_HOST
        fromDatabase:
          name: tabulador-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: tabulador-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: tabulador-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tabulador-db
          property: password
      - key: HASH_SALT
        value: 10
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: tabulador-db
    plan: free
    databaseName: tabulador_pg
    user: tabulador_user